# ETL Configuration for Customer Data Processing

# BigQuery Table Configuration
tables:
  destination: "c4-marketing-dev-347012.customer_data.customer_data_test"
  sources:
    line_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.a_ww_sales_trx_line"
    header_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.a_ww_sales_trx_header"
    card_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.d_card"
    site_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.d_ww_oc_site"
    store_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.d_ww_store"

# Processing Configuration
processing:
  # Maximum number of concurrent workers
  max_workers: 8
  
  # Query timeout in seconds
  query_timeout: 3600
  
  # BigQuery geographic location
  location: "EU"

# Filtering Configuration
filters:
  # Countries to process
  allowed_countries:
    - "ITA"
    - "ESP"
  
  # Country code mappings
  country_mapping:
    "ITA": "IT"
    "ESP": "SP"
  
  # Excluded chain types
  excluded_chain_types:
    - "SUPECO"
    - "Galerie"
    - "AUTRES"

# Job Configuration
job:
  # Maximum runtime in seconds (24 hours)
  max_runtime: 86400
  
  # Safety margin before job timeout (30 minutes)
  timeout_safety_margin: 1800
  
  # Optional: Specify specific months to process
  # start_month: "2025-01-01"
  # end_month: "2025-02-01"
  
  # Or process last N months
  last_n_months: 3
  
  # Whether to process months in parallel
  parallel: true

# Resilience Configuration
resilience:
  # Enable automatic retries for transient failures
  enable_retries: true
  
  # Maximum retry attempts
  max_retry_attempts: 5
  
  # Circuit breaker settings
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 300

# Logging Configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, or CRITICAL
  level: "INFO"