# ETL Configuration for Customer Data Processing

# BigQuery Table Configuration
tables:
  destination: "c4-marketing-dev-347012.customer_data.customer_data_test"
  sources:
    line_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.a_ww_sales_trx_line"
    header_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.a_ww_sales_trx_header"
    card_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.d_card"
    site_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.d_ww_oc_site"
    store_table: "c4-united-datasharing-prd.datasharing_marketing_group_dashboard.d_ww_store"

# Processing Configuration
processing:
  # Query timeout in seconds
  query_timeout: 3600
  
  # Maximum number of concurrent workers
  max_workers: 8
  
  # BigQuery geographic location
  location: "EU"

# Temporary Tables Configuration
temp_tables:
  # Hours before temporary tables are considered orphaned and cleaned up
  cleanup_age_hours: 24
  # Hours before temporary tables expire (BigQuery table expiration)
  expiration_hours: 24
  # Whether to add descriptions to temporary tables
  add_descriptions: true

# Countries Configuration
countries:
  # Country code mappings
  mapping:
    "ITA": "IT"
    "ESP": "SP"
  
  # Enabled countries
  enabled:
    - "ITA"
    - "ESP"
  
  # Country-specific filters
  filters:
    # Italy-specific filters
    ITA:
      excluded_chain_types:
        - "SUPECO"
        - "Galerie"
        - "AUTRES"
      excluded_site_types: []
    
    # Spain-specific filters
    ESP:
      excluded_business_brands:
        - "supeco"
      excluded_ecm_combinations:
        - business_brand: "alcampo"
          activity_type: "ECM"
      excluded_chain_types: []

# Job Configuration
job:
  # Process last N months
  last_n_months: 3
  
  # Whether to process months in parallel
  parallel: true

# Resilience Configuration
resilience:
  # Maximum retry attempts
  max_retry_attempts: 5

# Logging Configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, or CRITICAL
  level: "DEBUG"